### ISSUE TITLE
Cannot open human pose estimation project

### ISSUE THREAD

**Issue by rushi-the-neural-arch** [robertklee/COCO-Human-Pose#41]
Hi, I was actually looking for a way to deploy image segmentation project and mainly I wanted to see if I can use spaces to take raw video feed from my webcam as input and use various models to check the segmentation live on the web. Is it possible to do such live testing using spaces??

**Comment by robertklee** [comment]
Thank you for bringing this up. It looks like an update to a dependency removed support for a function a different dependency needed. I have pinned the versions at fault and rebooted the app.
