### ISSUE TITLE
Missing from streamlit gallery

### ISSUE THREAD

**Issue by gurbaaz27** [robertklee/COCO-Human-Pose#42]
Hello!
It is more of a query rather than an issue, but I cannot find the deployed demo app which was earlier present in gallery on Streamlit's official site.

Is there any particular reason behind it? If yes, when would it be back up?

Thanks.

**Comment by robertklee** [comment]
Hi there,

Thanks for filing this issue! There was a dependency that was updated and failed. I've resolved the issue and the demo is back up.
